feat: poc analytics
voiceflow/general-runtime pull request #135
Opened 2021-06-11 17:21 UTC by xavidop

**Fixes or implements VF-XXX**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

### Checklist

- [ ] title of PR reflects the branch name
- [ ] all commits adhere to conventional commits
- [ ] appropriate tests have been written
- [ ] all the dependencies are upgraded

2021-06-21 18:09 UTC, frankgu968 commented
Looks good to me overall. I'd move the debug calls to the trace level to avoid polluting the logs when we are actually debugging. The JSON body is quite large and verbose.

2021-06-28 04:41 UTC, jonahsnider requested changes
Looks good overall, just needs some unit tests. There are also a few very minor issues I pointed out. I'd be happy to make those changes if you'd like.

2021-06-28 04:41 UTC, jonahsnider commented on lib/clients/analytics.ts
> +  private analyticsClient: any;
We should be doing our best to avoid using `any` types in the source as it makes it very difficult for other developers to maintain in the future.

2021-06-28 04:41 UTC, jonahsnider commented on lib/clients/analytics.ts
> +    if (metadata.data && metadata.data.reqHeaders && metadata.data.reqHeaders.sessionid) {
We can use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to clean up logic like this:
```suggestion
    if (metadata.data?.reqHeaders?.sessionid) {
```

2021-06-28 04:41 UTC, jonahsnider commented on lib/clients/ingest-client.ts
> +  public static getInstance(endpoint: string, auhtorization: string) {
This pattern of having a static `getInstance()` method is not really the idiomatic way to work in JS/TS. It's totally fine to just export a single instance of the class if you really need a singleton to work with. [The TypeScript docs explain this in a bit more detail here](https://www.typescriptlang.org/docs/handbook/2/classes.html#why-no-static-classes).

2021-06-28 17:25 UTC, xavidop commented on lib/clients/ingest-client.ts
> +  public static getInstance(endpoint: string, auhtorization: string) {
fixed!

2021-06-28 17:25 UTC, xavidop commented on lib/clients/analytics.ts
> +    if (metadata.data && metadata.data.reqHeaders && metadata.data.reqHeaders.sessionid) {
fixed!

2021-06-28 17:25 UTC, xavidop commented on lib/clients/analytics.ts
> +  private analyticsClient: any;
fixed

2021-06-29 17:04 UTC, DecathectZero commented on types.ts
> +    sessionid?: string;
just for minor styling - https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive#:~:text=Header%20names%20are%20not%20case,%22)%20and%20the%20field%20value.

```suggestion
    sessionId?: string;
```

2021-06-29 18:19 UTC, DecathectZero commented
front end component to this PR:
https://github.com/voiceflow/creator-app/pull/3599

2021-06-29 21:02 UTC, jonahsnider approved these changes

2021-06-29 21:03 UTC, jonahsnider commented
waiting for final approval from @xavidop then we can merge this

2021-06-30 09:25 UTC, merged

2021-06-30 09:28 UTC, vf-service-account commented
:tada: This PR is included in version 1.49.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@voiceflow/general-runtime/v/1.49.0)
- [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.49.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: