ci(circleci): added docker lint, source lint, unit test steps
voiceflow/general-runtime pull request #20
Opened 2021-01-12 11:09 UTC by xavidop

2021-01-13 15:23 UTC, frankgu968 approved these changes

2021-01-13 16:43 UTC, frankgu968 requested changes

2021-01-13 16:43 UTC, frankgu968 commented on package.json
> +    "test:single": "NODE_ENV=test ts-mocha --paths --opts ./config/tests/single/mocha.single.opts",
Move the single test config to `./config/tests`

2021-01-13 16:43 UTC, frankgu968 commented on .circleci/config.yml
> +  vfcommon: voiceflow/common@0.0.43
Update to 0.0.44 or latest

2021-01-13 19:19 UTC, xavidop commented on .circleci/config.yml
> +  vfcommon: voiceflow/common@0.0.43
done

2021-01-13 19:19 UTC, xavidop commented on package.json
> +    "test:single": "NODE_ENV=test ts-mocha --paths --opts ./config/tests/single/mocha.single.opts",
done

2021-01-13 20:06 UTC, leartgjoni-voiceflow approved these changes

2021-01-14 14:33 UTC, frankgu968 approved these changes

2021-01-20 21:07 UTC, merged

2021-01-20 21:09 UTC, vf-service-account commented
:tada: This PR is included in version 1.12.1 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.12.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: