Set user_id to UserId for state api calls
voiceflow/general-runtime pull request #215
Opened 2021-11-03 18:28 UTC by ConnorByers

**Fixes or implements VF-2153**

### Brief description. What is this change?

Made user_id variable reflect the UserID passed in the network request for state api requests (see: https://www.voiceflow.com/api/dialog-manager#operation/stateInteract ).

### Implementation details. How do you make this change?

For first time UserIDs, the user_id variable is set in the initial generation of the context. See lib/services/state/index.ts StateManager generate.

For existing userIds to be able to access the user_id, the addition of the variable is done in the case of a LAUNCH request. I thought it would be overkill to set it for every state api request, so a reset for any user will add the ability to use the user_id variable.

### Setup information

### Deployment Notes

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2021-11-03 18:29 UTC, ConnorByers commented
Only mild testing done due to being blocked to general-service prototype jobs not working for me.

2021-11-03 19:20 UTC, leartgjoni-voiceflow requested changes
the API supports the ability to start a conversation with an Intent request (matching one of the open intents as the starting block) hence it can't be set only for launch requests. I think the easiest way is to follow the same pattern we use for the [timestamp variable](https://github.com/voiceflow/general-runtime/blob/75816eeda662edc5cfe459063451442bb82c7d3a/lib/services/runtime/index.ts#L69)

2021-11-05 14:15 UTC, leartgjoni-voiceflow approved these changes

2021-11-05 21:15 UTC, merged

2021-11-05 21:35 UTC, vf-service-account commented
:tada: This PR is included in version 1.65.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@voiceflow/general-runtime/v/1.65.0)
- [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.65.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: