feat: no-reply/no-match improvements (VF-1997)
voiceflow/general-runtime pull request #227
Opened 2021-11-23 19:00 UTC by z4o4z

**Fixes or implements VF-1997**

### Related PRs
https://github.com/voiceflow/libs/pull/115

2021-11-23 19:52 UTC, DecathectZero commented on lib/services/runtime/handlers/noReply.ts
> +      : nonEmptyNoReplies?.[runtime.storage.get<NoMatchCounterStorage>(StorageType.NO_REPLIES_COUNTER)! - 1];
```suggestion
      : nonEmptyNoReplies?.[noReplyCounter];
```

move line 44 (increment) after this to make it easier to read

2021-11-23 20:38 UTC, DecathectZero requested changes
`request: null` might not be the best implementation here, because we've essentially tied `null` to the launch function. Like you mentioned earlier:

https://github.com/voiceflow/general-runtime/blob/a8da9c94b2fcb72687d6ad8fe318c56c43c762e8/runtime/lib/Runtime/index.ts#L148

When you start the prototype tool, it sends a `request: null`, and will ALWAYS trigger the no reply logic. The only alternative I've found to this is changing the line above to just `this.setAction(Action.REQUEST)` and in the start block doing: 
<img width="512" alt="Screen Shot 2021-11-23 at 9 37 54 PM" src="https://user-images.githubusercontent.com/5643574/143104907-e626dd04-5c99-4654-909b-60a2f73885d7.png">

Although I do worry about the side effects.

2021-11-23 23:23 UTC, DecathectZero commented
I'm hoping this fixes a lot of the actions/request/response issues:
https://github.com/voiceflow/general-runtime/pull/228

2021-11-24 17:49 UTC, DecathectZero commented on lib/services/runtime/utils.ts
> +export const removeEmptyPrompts = (prompts: Array<Text.SlateTextValue | string>): Array<Text.SlateTextValue | string> =>
shouldn't this mostly be done on the service?

2021-11-24 23:37 UTC, DecathectZero commented on lib/services/runtime/handlers/noMatch.ts
> +  } as NoMatchNode);
this is the one hack I have to do....the union type on `NoMatchNode` gets mad :(

2021-11-25 08:51 UTC, z4o4z commented on lib/services/runtime/utils.ts
> +export const removeEmptyPrompts = (prompts: Array<Text.SlateTextValue | string>): Array<Text.SlateTextValue | string> =>
we have it in the service too, but on runtime, we are injecting variables, and some prompts can be empty due to empty strings in vars

2021-11-25 15:33 UTC, DecathectZero approved these changes

2021-11-25 16:02 UTC, DecathectZero commented on lib/services/runtime/handlers/noMatch.ts
> +    if (noMatchCounter >= nonEmptyNoMatches.length) {
```suggestion
    if (noMatchCounter > nonEmptyNoMatches.length) {
```

2021-11-25 16:04 UTC, DecathectZero commented on lib/services/runtime/handlers/noMatch.ts
> +    const noMatchCounter = runtime.storage.get<NoMatchCounterStorage>(StorageType.NO_MATCHES_COUNTER) ?? 0;
```suggestion
    const noMatchCounter = runtime.storage.get<NoMatchCounterStorage>(StorageType.NO_MATCHES_COUNTER) ?? 1;
```

2021-11-25 17:26 UTC, merged

2021-11-25 17:42 UTC, vf-service-account commented
:tada: This PR is included in version 1.70.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@voiceflow/general-runtime/v/1.70.0)
- [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.70.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: