feat: api block localization
voiceflow/general-runtime pull request #234
Opened 2021-12-13 16:39 UTC by ConnorByers

**Fixes or implements VF-2376**

### Brief description. What is this change?

Change api block implementation to make calls within general-service vs custom-api. 

### Implementation details. How do you make this change?

We use redis to keep track out of outgoing calls and throttle if exceeds limits.
We limit the response size of api calls to prevent massive calls through the request config in axios.

### Setup information

### Deployment Notes

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2021-12-13 16:41 UTC, ConnorByers commented
Some things for debate:
-Limit api call amounts for private/public
-time to reset tracking in redis
-throttling time amount

2021-12-13 17:03 UTC, jonahsnider commented on runtime/lib/Runtime/OutgoingApiLimiter/index.ts
> +  }
instead of writing `Number(getHostnameUses())` you should just alter this function to return `number | null` directly

```suggestion
  private async getHostnameUses(hostname: string): Promise<number | null> {
    const uses = await this.runtime.services.redis.get(this.makeRedisHostnameHash(hostname));
    
    return uses ? Number(uses) : null;
  }
```

2021-12-13 17:03 UTC, jonahsnider commented on runtime/lib/Runtime/index.ts
>    ) {
i think eslint is right here, is it possible to combine anything here into an object?

2021-12-13 17:03 UTC, jonahsnider commented on runtime/lib/Handlers/api/utils.ts
> +    throw new Error();
this is still kinda strange. is there a reason we can't just do

```suggestion
    throw e;
```

2021-12-13 18:45 UTC, trs requested changes

2021-12-13 18:45 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +const PROHIBITED_IP_RANGES = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', '127.0.0.0/8', '0.0.0.0/8', 'fd00::/8', '169.254.169.254/32'];
Are these typical "local" IPs?

2021-12-13 18:45 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +  });
I think using some more specific array methods can help clarify this piece of code:

```suggestion
  const badIP = ips.find((ip) => PROHIBITED_IP_RANGES.some((range) => ipRangeCheck(ip, range)));
  if (badIP) {
    throw new VError(`url resolves to IP: ${badIP} in prohibited range`, VError.HTTP_STATUS.BAD_REQUEST);
  }
```

2021-12-13 18:45 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +  });
`Array.prototype.some` could be used here too.

```suggestion
  if (BLACKLISTED_URLS.some((regex) => regex.test(url))) {
    throw new VError('url endpoint is blacklisted', VError.HTTP_STATUS.BAD_REQUEST);
  }
```

2021-12-13 18:45 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +    });
Can build an object using `Object.fromEntries`.

```suggestion
    const formattedParams = Object.fromEntries(params.map((param) => [param.key, param.val]));
```

2021-12-13 18:45 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +    });
```suggestion
    const formattedHeaders = Object.fromEntries(headers.map((header) => [header.key, header.value]));
```

2021-12-13 18:45 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +  if (method !== 'GET') {
Looking at the previous code, these changes seem to make this less readable and more confusing. I'd recommend taking another go at this.

2021-12-13 18:45 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +    }
Trying to utilize the array methods better.

```suggestion
    const newVariables = Object.fromEntries((data.mapping ?? [])
      .filter((map) => map.var)
      .map((map) => [map.var, getVariable(m.path, response.data)])
    );
```

2021-12-13 18:49 UTC, jonahsnider commented on runtime/lib/Handlers/api/utils.ts
> +  if (method !== 'GET') {
i agree. is it possible to split this up into a bunch of smaller functions?

2021-12-13 19:27 UTC, ConnorByers commented on runtime/lib/Handlers/api/utils.ts
> +  if (method !== 'GET') {
I copied all of this code directly from `custom-api`. The version existing in `general-runtime` previously was just a simplified version by Leart I believe. I'll break it up though

2021-12-13 19:43 UTC, ConnorByers commented on runtime/lib/Handlers/api/utils.ts
> +const PROHIBITED_IP_RANGES = ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', '127.0.0.0/8', '0.0.0.0/8', 'fd00::/8', '169.254.169.254/32'];
I took these directly from `custom-api`. Some are localhost and some are private ip ranges.

2021-12-14 15:31 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +  }
This should probably go in the `validateUrl` function, yeah?

2021-12-14 15:31 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +    if (typeof data === 'object' && options !== null) {
Be aware that `data` maybe not be a record since other types are "objects".

```
> typeof null
'object'
> typeof []
'object'
```

2021-12-14 15:31 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +  }
Instead of checking this here, we could consider this function a pure type validator, and move it out to the `makeAPICall` function. Since this isn't so much validating as looking up and delaying. That way this function doesn't have to be async too.
What do you think?

2021-12-14 19:23 UTC, ConnorByers commented on runtime/lib/Handlers/api/utils.ts
> +  }
Taking it out makes sense, the function will remain async because of the code block inside:
```
// DNS.resolve returns an array of ips
  const ips = validator.isIP(hostname)
    ? [hostname]
    : await DNS.resolve(hostname).catch(() => {
        throw new VError(`cannot resolve hostname: ${hostname}`, VError.HTTP_STATUS.BAD_REQUEST);
      });
```

2021-12-14 19:45 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +  }
Good point.
Maybe we should move that out too? It kinda seems like a separate concern.

Steps seem to be:

- Get IP from hostname
- Validate IP
- Make request to IP
  - Rate limit request to IP

Really, each could be their own function.

2021-12-14 19:46 UTC, trs approved these changes

2021-12-15 15:04 UTC, DecathectZero commented on runtime/lib/Runtime/OutgoingApiLimiter/index.ts
> +    return `${this.REDIS_PREFIX}_${this.isPublic() ? 'public' : this.runtime.authorization!}_${hostname}`;
I think maybe we just use `versionID` and have the same number for both public and private?

2021-12-15 19:35 UTC, merged

2021-12-15 19:54 UTC, vf-service-account commented
:tada: This PR is included in version 1.73.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@voiceflow/general-runtime/v/1.73.0)
- [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.73.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: