ci: new cicd system
voiceflow/general-runtime pull request #261
Opened 2022-01-13 10:10 UTC by xavidop

**Fixes or implements VF-2657**

### Brief description. What is this change?

Implements [this](https://www.notion.so/voiceflow/CI-CD-System-f80ef4dd66b8407ba23f7a72e097b96d)

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2022-01-13 10:27 UTC, xavidop commented
bors try

2022-02-01 17:06 UTC, xavidop commented
bors try

2022-02-03 00:19 UTC, frankgu968 requested changes

2022-02-03 00:19 UTC, frankgu968 commented on .circleci/config.yml
> +  vfcommon: voiceflow/common@dev:8c5ebfe
fix this once the orb is published

2022-02-03 00:19 UTC, frankgu968 commented on Dockerfile
>  FROM node:16-alpine
it just occurred to me: if we are using node:16-alpine as the runtime container, would the built artifacts work? because the build might be done on a different environment

2022-02-03 10:01 UTC, xavidop commented on Dockerfile
>  FROM node:16-alpine
the docker image we are using for build it's using the same docker image: 168387678261.dkr.ecr.us-east-1.amazonaws.com/ci-node-build-image:v1

https://github.com/voiceflow/infrastructure/blob/master/utils/circleci/Dockerfile.node.build

2022-02-03 10:01 UTC, xavidop commented on .circleci/config.yml
> +  vfcommon: voiceflow/common@dev:8c5ebfe
yup

2022-02-06 12:41 UTC, frankgu968 approved these changes

2022-02-09 12:12 UTC, xavidop commented
bors r+

2022-02-09 12:27 UTC, closed without merging