refactor: update libs and fix lint issues (VF-3118)
voiceflow/general-runtime pull request #312
Opened 2022-05-05 09:30 UTC by pmvrmc

**Fixes or implements VF-3118**

### Brief description. What is this change?

Setting up new versions of linter and its plugins and fixing the lint issues

### Implementation details. How do you make this change?

some are fixed through yarn lint:quiet --fix others manually

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

2022-05-05 18:56 UTC, jonahsnider requested changes

2022-05-05 18:56 UTC, jonahsnider commented on runtime/lib/Runtime/Store/index.ts
> +}
```suggestion
export type State = Readonly<Record<string, any>>;
```

2022-05-05 18:56 UTC, jonahsnider commented on runtime/lib/Runtime/Store/index.ts
>      return this.store[key];
unrelated to this PR but are we actually using a plain object as a KV-store with arbitrary keys? this seems like a prototype pollution vulnerability...

2022-05-05 18:56 UTC, jonahsnider commented on tests/lib/services/dialog/fixture.ts
> +} as any as CacheDataAPI;
```suggestion
} as unknown as CacheDataAPI;
```

2022-05-05 21:26 UTC, trs commented on lib/services/nlu/nlc.ts
>          const matcher = _.flatten(slot.inputs.map((input) => input.split(',')))
```suggestion
        const matcher = slot.inputs.flatMap((input) => input.split(','))
```

2022-05-05 21:26 UTC, trs commented on lib/services/runtime/handlers/utils/entity.ts
> +    const intentsArray = intents ?? [];
I'm not a fan of this pattern, since it's very easy to accidentally use the original parameter, instead of this "fixed" value.

These cases I'd prefer reassigning the parameter.

But ideally a default in the parameter is better. What rule is preventing that?

2022-05-05 21:26 UTC, trs commented on lib/services/runtime/handlers/utils/entity.ts
> +    const priorIntentMatch = intentsArray.includes(priorIntent?.payload.intent.name!) && priorIntent?.payload.entities.length;
Probably best to avoid asserting here. Can we do something like this?

```suggestion
    const priorIntentMatch = !!priorIntent && intentsArray.includes(priorIntent.payload.intent.name) && priorIntent.payload.entities.length;
```

2022-05-05 21:26 UTC, trs commented on lib/services/runtime/utils.ts
> +    value && typeof value.valueOf() === 'string' ? replaceVariables(value, variables, undefined, { trim: false }) : undefined;
```suggestion
    value && typeof value === 'string' ? replaceVariables(value, variables, undefined, { trim: false }) : undefined;
```

2022-05-05 21:26 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +  if (str && typeof str.valueOf() === 'string' && !Number.isNaN(str as any) && str.length < 16) {
```suggestion
  if (str && typeof str === 'string' && !Number.isNaN(Number(str)) && str.length < 16) {
```

2022-05-05 21:26 UTC, trs commented on runtime/lib/Runtime/Store/index.ts
> +}
`base-types` even has a `AnyRecord`.

2022-05-05 21:26 UTC, trs commented on runtime/lib/Runtime/Store/index.ts
>      return this.store[key];
Probably worth changing this to a `Map` anyway.

2022-05-05 21:28 UTC, jonahsnider commented on lib/services/runtime/handlers/utils/entity.ts
> +    const priorIntentMatch = intentsArray.includes(priorIntent?.payload.intent.name!) && priorIntent?.payload.entities.length;
yes, do that or do `priorIntent!.whatever`

2022-05-05 21:29 UTC, jonahsnider commented on lib/services/runtime/handlers/utils/entity.ts
> +    const intentsArray = intents ?? [];
there's a rule that enforces optional parameters being last. optional meaning "a parameter with a default assignment". trying to rearrange arguments can be annoying or can cause problems when there are multiple optional params

2022-05-09 08:34 UTC, pmvrmc commented on lib/services/dialog/utils.ts
>  };
good call, there were only a few occurences so I change it to your suggestion 👍

2022-05-09 09:06 UTC, pmvrmc commented on lib/services/runtime/handlers/utils/entity.ts
> +    const priorIntentMatch = intentsArray.includes(priorIntent?.payload.intent.name!) && priorIntent?.payload.entities.length;
ty for the suggestion, makes more sense, will use it :)

2022-05-09 09:13 UTC, pmvrmc commented on runtime/lib/Handlers/api/utils.ts
> +  if (str && typeof str.valueOf() === 'string' && !Number.isNaN(str as any) && str.length < 16) {
got it, fixed!

2022-05-09 09:14 UTC, pmvrmc commented on runtime/lib/Handlers/ifV2.ts
> +    const setOutputPort = function (index: number) {
Im also not sure, but left it as is to not make more changes. Do you feel I should change it?

2022-05-09 09:15 UTC, pmvrmc commented on runtime/lib/Runtime/Store/index.ts
>      return this.store[key];
Not sure what would be the correct change here, I left it as is for now, if you think I should make more changes just ping me

2022-05-09 16:13 UTC, closed without merging