feat: add custom action isBlocking checkbox support (VF-3675)
voiceflow/general-runtime pull request #342
Opened 2022-06-20 16:11 UTC by pmvrmc

**Fixes or implements VF-3675**

### Brief description. What is this change?

If a custom action sets the isBlocking checkbox that is now propagated to the runtime

### Related PRs

- https://github.com/voiceflow/general-service/pull/358

2022-06-21 17:18 UTC, trs commented on lib/services/runtime/handlers/_v1.ts
> +      stop,
Again, I don't see why we'd need this. The runtime won't send any more traces if `stop` is true.

2022-06-21 17:18 UTC, trs requested changes
Let's discuss this

2022-06-22 10:11 UTC, pmvrmc commented on lib/services/runtime/handlers/_v1.ts
> +      stop,
it wont send any more traces, but how the client/adapter handles it is different.

If the custom action is `stop` (or we send it on the stopTypes) the client needs to call interact again to proceed with the flow. Otherwise it can just handle that specific trace and the also the other ones.

This is basically syntatic sugar for not needing to add/check the stopTypes. The trace itself should hold all the information needed to handle it.

2022-06-23 14:24 UTC, closed without merging

2022-06-23 14:25 UTC, vf-service-account commented
Dev environment review-lingering-forest destroyed!