refactor: versioned API routes (VF-0000)
voiceflow/general-runtime pull request #348
Opened 2022-06-23 05:19 UTC by MrPicklePinosaur

**Fixes or implements VF-0000**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2022-06-30 20:13 UTC, trs requested changes
If we're introducing a v2 we should put some improvements in place:
- A single "way" of calling interact. No more "legacy" routes.
- Improving the request
  - Remove some odd configs
  - No more stateful + stateless routes: single method
- Improving the response
  - Remove `stack`, this is a runtime implementation detail

We should also organize these better. We should group by domain and not by version. So have interact routes together declared with their version and path together, not all v1 together, etc. It's much harder to find a route when organized by version.

These new version were brought up with the new custom action format right? But I don't see where we are introducing that or adding the transformation back in the legacy routes.

2022-06-30 20:13 UTC, trs commented on lib/controllers/v2alpha/stateless/index.ts
> + */
I've never seen this before, is it some sort of documentation generation?

2022-06-30 20:13 UTC, trs commented on backend/api/routers/v2alpha/stateful/index.ts
> +  // Legacy 1.0.0 routes with versionID in params
Why should we have legacy routes in a v2?

2022-06-30 20:55 UTC, MrPicklePinosaur commented on backend/api/routers/v2alpha/stateful/index.ts
> +  // Legacy 1.0.0 routes with versionID in params
seems like i messed something up when refactoring - whoops

2022-06-30 20:59 UTC, MrPicklePinosaur commented
> 

this PR was meant to get the basis of the versioning set up - so `v2alpha` at the moment is just a duplicate of `v1`. [https://github.com/voiceflow/general-runtime/pull/340] is meant to follow up and actually apply all the `v2alpha` changes

2022-06-30 20:59 UTC, MrPicklePinosaur commented on lib/controllers/v2alpha/stateless/index.ts
> + */
hm im not sure, it seems to have been present in the old code

2022-07-05 17:00 UTC, MrPicklePinosaur commented
fyi: the tests for general-runtime routes are not very good, could use some rewrite in the future

2024-03-23 16:54 UTC, closed without merging