feat: gotonode handler (CT-252)
voiceflow/general-runtime pull request #356
Opened 2022-06-24 13:01 UTC by z4o4z

**Fixes or implements VF-252**

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2022-06-24 13:38 UTC, pmvrmc reviewed
curious, seems lib/services/runtime/handlers/gotoNode.ts and runtime/lib/Handlers/gotoNode.ts have the same exact content, do we really need both?

2022-06-24 22:04 UTC, trs requested changes

2022-06-24 22:04 UTC, trs commented on lib/services/runtime/handlers/gotoNode.ts
> +import { BaseNode, BaseTrace } from '@voiceflow/base-types';
We shouldn't be duplicating these handlers. We can just import the other handler from `@/runtime` in [the handler setup](https://github.com/voiceflow/general-runtime/blob/master/lib/services/runtime/handlers/index.ts).

2022-06-27 05:34 UTC, DecathectZero commented on lib/services/runtime/handlers/gotoNode.ts
> +import { BaseNode, BaseTrace } from '@voiceflow/base-types';
what handlers are we duplicating here

2022-06-27 05:40 UTC, DecathectZero commented on lib/services/runtime/handlers/gotoNode.ts
> +    runtime.stack.popTo(frameIndex + 1);
if the diagram doesn't exist in the stack `findIndex` is going to pop it all the way down to -1 for `frameIndex`.

If it goes to 0 we will be removing the `baseProgram` (which ties together all the topics with global intents)

I guess it's fine because we inject it back in every single update cycle? So by the time the next response comes in it should be okay.
https://github.com/voiceflow/general-runtime/blob/master/runtime/lib/Runtime/index.ts#L160

2022-06-27 05:42 UTC, DecathectZero approved these changes
Let's combine
`lib/services/runtime/handlers/gotoNode.ts`
`runtime/lib/Handlers/gotoNode.ts`
together so we can reuse the code?

2022-06-29 08:46 UTC, z4o4z commented
> curious, seems lib/services/runtime/handlers/gotoNode.ts and runtime/lib/Handlers/gotoNode.ts have the same exact content, do we really need both?

yeah, I just moved it from services to the platform but forgot to remove the original file, thanks! :)

2022-06-29 08:51 UTC, z4o4z commented on lib/services/runtime/handlers/gotoNode.ts
> +import { BaseNode, BaseTrace } from '@voiceflow/base-types';
yeah, just forgot to remove service one after moving the handler to platform folder :)

2022-06-29 10:07 UTC, z4o4z commented
bors r+

2022-06-29 10:33 UTC, z4o4z commented
bors r+

2022-06-29 15:14 UTC, z4o4z commented
bors r+

2022-06-29 15:28 UTC, closed without merging