feat: remove creator-api dependency (VF-3982)
voiceflow/general-runtime pull request #364
Opened 2022-06-30 00:07 UTC by trs

**Fixes or implements VF-3982**

### Brief description. What is this change?

Remove the dependency on `creator-api` all together, rely instead on the `server-data-api`.

Environment variables no longer needed:
- `CREATOR_API_AUTHORIZATION`
- `CREATOR_API_ENDPOINT`

2022-06-30 01:39 UTC, zhihil requested changes

2022-06-30 01:39 UTC, zhihil commented on runtime/lib/DataAPI/serverDataAPI.ts
> +    const [, , apiKeyID] = split.length === 4 ? split : ['', ...split];
This line of code feels a little arcane. Although less concise, it might be worth using `isDMAPIKey()` and `isWorkspaceAPIKey()` to spell out for the reader why `split.length === 4` or `split.length !== 4` are different cases.

2022-06-30 01:39 UTC, zhihil commented on runtime/lib/DataAPI/serverDataAPI.ts
> +
How does this handle the case where `authorization` is `undefined`? I don't think we ever figured out the black magic of how the prototype tool is able to contact creator without the authorization.

2022-06-30 01:39 UTC, zhihil commented on lib/services/state/cacheDataAPI.ts
> +    return apiKey as VoiceflowProject.Project;
Is the naming here incorrect? It should be `const project = await` not `const apiKey = `?

2022-06-30 01:57 UTC, zhihil commented on runtime/lib/DataAPI/serverDataAPI.ts
> +
Nevermind, tested on the prototype tool. This appears to work.

2022-07-02 18:35 UTC, trs commented on runtime/lib/DataAPI/serverDataAPI.ts
> +    const [, , apiKeyID] = split.length === 4 ? split : ['', ...split];
Added a helper to use here: https://github.com/voiceflow/libs/pull/316

2022-07-04 18:35 UTC, zhihil requested changes

2022-07-04 18:35 UTC, zhihil commented on lib/middlewares/project.ts
> +      const project = await api.getProjectUsingAPIKey(req.headers.authorization!).catch(() => {
Don't forget to change the check here `(!Utils.object.hasProperty(api, 'getProjectUsingAuthorization'))` in this file to
```js
(!Utils.object.hasProperty(api, 'getProjectUsingAPIKey'))
```
One of my tests just failed because the check was not updated to this new method name.

2022-07-04 20:43 UTC, trs commented
This change is a bit premature since there is no authorization in place to restrict which projects/versions a key has access to.
Instead we can retain the creator api call until the authorization revamp is further along.

2022-07-04 20:43 UTC, closed without merging