feat: use auth service (PL-71)
voiceflow/general-runtime pull request #390
Opened 2022-07-29 10:51 UTC by jonahsnider

**Fixes or implements PL-71**

### Brief description. What is this change?

remove all references to creator-api

use server-data-api directly & do authorization checks with the auth service

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written

2022-08-01 20:25 UTC, trs requested changes

2022-08-01 20:25 UTC, trs commented on lib/clients/auth.ts
> +export enum Permission {
I feel like just restricting this to what permissions are actually used here is probably better. We can explore places to declare these in a sharable manner in the future.

2022-08-01 20:25 UTC, trs commented on lib/middlewares/auth.ts
> +  async assertPermissionsMiddleware(_req: Request, _res: Response, next: express.NextFunction): Promise<void | never> {
In the future we should explore providing a middleware from the sdk directly.

2022-08-01 20:25 UTC, trs commented on lib/middlewares/auth.ts
> +        `ApiKey ${req.headers.authorization}`,
Yep, we'd need to check if it looks like an API key (starts with `VF.`), if it doesn't then the auth scheme is `Bearer`.
Can check out [`creator-api` when it does it's verification](https://github.com/voiceflow/creator-api/blob/master/lib/services/authManager/index.ts#L79).

2022-08-01 20:26 UTC, trs requested changes

2022-08-01 20:26 UTC, trs commented on package.json
> +    "@voiceflow/sdk-auth": "../platform/libs/sdk-auth/",
We'll have to wait till we have the CI setup to merge this too.

2022-08-01 20:26 UTC, trs commented on package.json
> +    "undici": "^5.8.0",
This includes node-fetch already, should we just use that?

2022-08-02 07:48 UTC, jonahsnider commented on lib/middlewares/auth.ts
> +  async assertPermissionsMiddleware(_req: Request, _res: Response, next: express.NextFunction): Promise<void | never> {
i'd like to if it'd be helpful, but it seems to me that there is very little that can be abstracted here (at least, if we want to reuse the middleware in other services)

2022-10-04 00:45 UTC, Xavientois commented on types.ts
> +  AUTH_SERVICE_ENDPOINT: string;
Since this is non-null, will it complain if `AUTH_SERVICE_ENDPOINT` is not set in the environment?

2022-10-04 00:47 UTC, jonahsnider commented on types.ts
> +  AUTH_SERVICE_ENDPOINT: string;
yes, because this value is populated with `getRequiredProcessEnv()` (which throws an error if the env var isn't defined)

which, now that i think about it, is a mistake most likely. this will break the runtime for selfhosters

2022-10-06 08:33 UTC, jonahsnider commented on types.ts
> +  AUTH_SERVICE_ENDPOINT: string;
i've updated the PR to make `AUTH_SERVICE_ENDPOINT` optional

2022-11-23 11:12 UTC, xavidop commented
bors ping

2022-11-23 11:15 UTC, xavidop commented
bors ping

2022-11-23 11:23 UTC, xavidop commented
bors ping

2022-11-23 11:29 UTC, xavidop commented
bors ping

2022-11-23 11:29 UTC, xavidop commented
LETS GOOO POOOOOOONG

2024-03-23 16:53 UTC, closed without merging