feat: upload custom tls certificate for api calls (PL-120)
voiceflow/general-runtime pull request #424
Opened 2022-10-06 19:59 UTC by AhmedVF

**Fixes or implements PL-120**

### Brief description. What is this change?

This PR does two things:
1. During runtime, when an API request needs to be made, we check to see if the corresponding node as any tls info. If it does, we use it to read the certificate and key from AWS S3, which we then use to create an agent which is included in the request. This allows us to use the certificate and key someone uploads to engage in a mutual tls connection with their server.
2. When editing their diagram, there is an option for someone to make a request to an API. Previously, `creator-app` made a request to the `creator-api`, which in turn made a request to `custom-api` which finally made a request to the user's API. Now, `creator-app` makes a request to `general-runtime` which follows the exact same steps to make the request as it does at runtime.

### Implementation details. How do you make this change?
- Add a createAgent function which is responsible for creating the agent with the tls info. This agent is then passed as a parameter to the request.
- Added some helper functions to create the S3 client and read from the bucket. These are used in the createAgent function.
- Added a new endpoint on `general-runtime` that `creator-app` calls when making the request from the editor.

### Setup information

Add the following env var. `S3_TLS_BUCKET="com.voiceflow.dev.api.images"`

### Deployment Notes

This requires the env var above to also be added for the production environment, but that has already been done in coordination with the infra team.

### Related PRs

https://github.com/voiceflow/general-service/pull/416

### Checklist

- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written
- [x] any new env vars have been added to the [notion doc](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb) and infra has been notified

2022-10-06 20:17 UTC, trs requested changes

2022-10-06 20:17 UTC, trs commented on .env.e2e
> +S3_TLS_BUCKET='com.voiceflow.dev.api.images'
I see a [request to create `API_IMAGE_BUCKET`](https://www.notion.so/voiceflow/Add-env-var-general-runtime-API_IMAGE_BUCKET-92cc2130af1e4402afbed34b71fbf2c5), but nothing about `S3_TLS_BUCKET`.
I don't think the general runtime needs `API_IMAGE_BUCKET`, but it does need `S3_TLS_BUCKET`.

2022-10-06 20:17 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
> +import CONFIG from '@/config';
This cannot be accessed here, since everything in the `runtime` folder is a library that other runtimes use. This is the reason for [the pattern of passing the values though when initializing the handler](https://github.com/voiceflow/general-runtime/pull/424/files#diff-de87f9769e26c15dc082d4959f9a1bfd5fe811a2a8d1e691b66e67d70b90ad66L35).

This will have to be changed to follow the existing patterns.

2022-10-06 20:24 UTC, jonahsnider commented on runtime/lib/Handlers/api/utils.ts
> +import CONFIG from '@/config';
note: i came up with this config code while pairing with ahmed. and totally forgot about where we're allowed to access `CONFIG`. sorry about that ahmed

how would you recommend properly passing the config here? make it a parameter to all the exported functions? and then pass `CONFIG` to the handler and then to the util functions, or, in the case of the new HTTP routes (which don't use the handler), just access `CONFIG` directly and pass it through

2022-10-06 20:55 UTC, AhmedVF commented on .env.e2e
> +S3_TLS_BUCKET='com.voiceflow.dev.api.images'
Sorry, you raise a good point. I originally asked infra to call the bucket `API_IMAGE_BUCKET` but we collectively decided on a new name. I didn't bother updating the request though since it had already been created, but I will do that for completeness.
Here's the slack convo if you're interested. https://voiceflowhq.slack.com/archives/C0411RY00BY/p1665072638157869

2022-10-06 21:01 UTC, AhmedVF commented on runtime/lib/Handlers/api/utils.ts
> +import CONFIG from '@/config';
Okay, let me try to get back to how it was before.

2022-10-07 15:52 UTC, AhmedVF commented on .env.e2e
> +S3_TLS_BUCKET='com.voiceflow.dev.api.images'
These docs have been updated.

2022-10-07 22:07 UTC, trs commented on lib/utils.ts
> +export const createResponseConfig = (config: Config): ResponseConfig => {
This is not a generic function, it is very specific to the api block, so it should not live in a generic utils place. This should probably just be applied in the api handler itself.

2022-10-07 22:07 UTC, trs commented on runtime/lib/Handlers/api/utils.ts
>  import VError from '@voiceflow/verror';
Outside of this PR, this whole file needs a revamp.

2022-10-07 22:16 UTC, jonahsnider commented on lib/utils.ts
> +export const createResponseConfig = (config: Config): ResponseConfig => {
is the API handler allowed to import the `Config` type?

2022-10-11 20:32 UTC, trs approved these changes

2022-10-11 20:32 UTC, trs commented on backend/api/index.ts
> +  router.use('/api', APIRouter(middlewares));
We should be a bit more specific with the route, `/api` is very generic.

2022-10-11 20:33 UTC, trs commented on lib/utils.ts
> +export const createResponseConfig = (config: Config): ResponseConfig => {
It is not, the `Config` type is at the app level, not the library level.

2022-10-11 21:23 UTC, AhmedVF commented on backend/api/index.ts
> +  router.use('/api', APIRouter(middlewares));
Updated to use `/test/api`

2022-10-12 21:46 UTC, AhmedVF commented
bors r+

2022-10-12 21:59 UTC, closed without merging