chore: remove references to workspace API key (PL-450)
voiceflow/general-runtime pull request #485
Opened 2023-02-27 23:55 UTC by astopo

**Fixes or implements PL-450**

### Brief description. What is this change?

Update docs - removes references to Workspace API Keys, except for errors.

### Checklist

- [ ] changes have been validated in an ephemeral environment
- [ ] this is a breaking change and should publish a new major version
- [ ] appropriate tests have been written
- [ ] any new env vars have been added to the [notion doc](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb) and infra has been notified

2023-02-28 00:18 UTC, trs commented on backend/docs/openapi.yaml
> +            3. `'Cannot resolve version alias from Workspace API key'` - Caller provided a legacy Workspace API key, which cannot
I think we could remove this outright. I'd say we treat a WS key in the authorization like any other invalid string, and not have a special error for it.

2023-02-28 00:18 UTC, trs approved these changes

2023-02-28 01:14 UTC, astopo commented on backend/docs/openapi.yaml
> +            3. `'Cannot resolve version alias from Workspace API key'` - Caller provided a legacy Workspace API key, which cannot
I agree - should we remove the error in this PR as well?

2023-02-28 02:48 UTC, trs commented on backend/docs/openapi.yaml
> +            3. `'Cannot resolve version alias from Workspace API key'` - Caller provided a legacy Workspace API key, which cannot
Yeah I think so

2023-02-28 15:04 UTC, astopo commented on backend/docs/openapi.yaml
> +            3. `'Cannot resolve version alias from Workspace API key'` - Caller provided a legacy Workspace API key, which cannot
@trs I got carried away and removed support for legacy Workspace Keys (along with the error) - but now rethinking that - do we actually want to continue to support them, even if the docs don't say that we do?

2023-02-28 15:28 UTC, trs requested changes

2023-02-28 15:28 UTC, trs commented on lib/middlewares/project.ts
> -        if (isVersionTag(req.headers.versionID)) {
I think we still need this, since if they don't give us a DM key but do give us a version tag, we can't resolve the version ID.
Can change the error to just a generic `Cannot resolve version alias` or something.

2023-02-28 21:21 UTC, astopo commented on lib/middlewares/project.ts
> -        if (isVersionTag(req.headers.versionID)) {
Okay, added back, and updated the error.

2023-03-03 02:21 UTC, trs commented on backend/docs/openapi.yaml
> +            3. `'Cannot resolve version alias from Workspace API key'` - Caller provided a legacy Workspace API key, which cannot
Yeah I'm thinking we should probably still support the code for now. It'll be unsupported when we move to the new auth service.

2023-03-05 17:38 UTC, trs commented on runtime/lib/DataAPI/utils.ts
> -  }
As discussed we should probably continue to support these. This PR should just be the docs

2023-03-06 18:01 UTC, trs approved these changes

2023-03-08 18:37 UTC, astopo commented
bors r+

2023-03-08 18:52 UTC, closed without merging