feat: add intent confidence to debug message
voiceflow/general-runtime pull request #58
Opened 2021-02-03 16:01 UTC by z4o4z

**Fixes or implements CORE-5004**

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

2021-02-03 18:52 UTC, effervescentia approved these changes

2021-02-03 18:53 UTC, effervescentia requested changes
should add tests for the new debug messages

2021-02-04 13:48 UTC, z4o4z commented
> should add tests for the new debug messages

we do not have tests for handlers at all, I guess we should create a ticket for next cooldown sprint to add tests for handlers

2021-02-04 18:59 UTC, DecathectZero requested changes
I think we should actually put the debug traces one level higher - in either the nlu/dialog handlers seen here https://github.com/voiceflow/general-runtime/blob/master/lib/controllers/interact.ts this way we don’t have to implement it for every single block, but rather when requests come in.

So I think the dialog handler or the very beginning of the runtime handler is a good place - as long as we receive an intent request we can show the trace.

2021-02-09 05:37 UTC, DecathectZero approved these changes

2021-02-09 05:40 UTC, merged

2021-02-09 05:43 UTC, vf-service-account commented
:tada: This PR is included in version 1.23.0 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: