feat: add moderation to llm calls (PL-553)
voiceflow/general-runtime pull request #588
Opened 2023-09-08 14:16 UTC by pmvrmc

**Fixes or implements PL-553**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

2023-09-08 15:49 UTC, vf-service-account commented
Creation of review environment failed! See details here: https://github.com/voiceflow/general-runtime/actions/runs/6123660107

2023-09-08 16:00 UTC, pmvrmc commented
env is https://creator-review-rough-mountain.na.development.voiceflow.com/

2023-09-27 14:49 UTC, zhihil commented on lib/clients/ai/types.ts
> +const LLM_MODERATION_FAIL_FF = 'LLM_MODERATION_FAIL_FF';
It would be best to put feature flag strings into a separate file, `libs/feature-flags` with:
```ts
enum FeatureFlag {
   LLMModerationFail = 'LLM_MODERATION_FAIL'
}
```

Scattering the flags will them hard to track down and manage.

2023-09-27 16:02 UTC, zhihil requested changes
The content moderation check has a bug. The AI refactor seems more or less fine. Most of the existing. functionality was preserved.

2023-09-27 16:07 UTC, pmvrmc commented on lib/clients/ai/types.ts
> +    }
1. the idea of the feature flag is to always call the moderation, but just error out if it fails. we want to leave it running for a while, check if there are many false positive or not and then turn it on.
2. you are right, when refactoring I removed the `failedModeation.length` check will add it back

2023-09-27 16:08 UTC, pmvrmc commented on lib/services/aiSynthesis.ts
> +      const generativeModel = this.services.ai.get(options.model);
good catch!

2023-09-27 16:11 UTC, pmvrmc commented on lib/clients/ai/types.ts
> +      this.openAIClient = new OpenAIApi(new Configuration({ apiKey: config.OPENAI_API_KEY }));
makes sense! I'll refactor to this idea 👍

2023-09-28 15:02 UTC, zhihil approved these changes
Code changes look good, ~~but I'm not able to find an example of a prompt that triggers our content moderation error, because OpenAI and Claude has built-in content moderation that filters out such content before it can reach our moderation. Please test the content moderation to ensure that it can detect true positives.~~

2023-09-28 15:33 UTC, pmvrmc commented
bors r+

2023-09-28 15:44 UTC, closed without merging