feat: update dependencies (CV3-361)
voiceflow/general-runtime pull request #591
Opened 2023-09-18 01:24 UTC by viniciusdacal

**Fixes or implements CV3-361**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

2023-09-19 02:50 UTC, DecathectZero commented on lib/controllers/stateManagement/requests.ts
> +    diagramID: StringField('diagramID'),
this might break some people calling our API, but I think it should be okay.

2023-09-19 14:32 UTC, viniciusdacal commented on lib/controllers/stateManagement/requests.ts
> +    diagramID: StringField('diagramID'),
Yeah, I think the alternative would be defining both properties and making none required, and adding `diagramID` as required a couple days after. 

But those errors should happen only if there's a conversation that started before the release, right? So I guess it's ok to break, because the person can just restart the conversation.

2023-09-27 14:20 UTC, z4o4z requested changes

2023-09-27 14:20 UTC, z4o4z commented on runtime/lib/DataAPI/localDataAPI.ts
> +  public getProgram = async (_versionID: string, diagramID: string) => this.programs[diagramID];
I assume `diagramID` is not unique (it's `diagramID` field not `_id`) here, right? if so we should cache programs per version just to be extra safe
```suggestion
  public getProgram = async (versionID: string, diagramID: string) => this.programs[versionID]?.[diagramID] ?? null;
```

2023-09-27 14:20 UTC, z4o4z commented on runtime/lib/DataAPI/mongoDataAPI.ts
>    public getProject = async (projectID: string) => {
looks like we should rename param
```suggestion
  public getProject = async (projectIDOrAuth: string) => {
```

2023-09-27 14:20 UTC, z4o4z commented on runtime/lib/DataAPI/mongoDataAPI.ts
> +  public getProjectByAPIKey = async (ref: string) => {
```suggestion
  public getProjectByAPIKey = async (auth: string) => {
```

2023-09-27 14:20 UTC, z4o4z commented on runtime/lib/Runtime/index.ts
> +        diagramID: this.versionID,
so we are storing `versionID` into a `diagramID`, probably it makes sense to have a different name in the `Frame` just to show not only `diagramID` is stored in this field...

```suggestion
        programID: this.versionID,
        // or
        frameID: this.versionID,
```

2023-09-27 14:20 UTC, z4o4z commented on runtime/lib/Runtime/utils/programManager.ts
> +    this.runtime.callEvent(EventType.programDidFetch, { programID: diagramID, program });
i guess we should add `versionID` into all vents that have `programID`. should we rename `programID` into `diagramID` here as well?

2023-09-27 17:13 UTC, viniciusdacal commented on runtime/lib/Runtime/index.ts
> +        diagramID: this.versionID,
No sure if I get the idea.

In this case, the `diagramID` will be the `versionID` because it's the base program. 
During the compilation we create a root program, which its `_id` and `diagramID` will be the same as the `versionID`.

That's why I think it still makes sense to keep the diagramID property.

2023-09-28 13:24 UTC, z4o4z approved these changes

2023-09-28 17:02 UTC, DecathectZero approved these changes

2023-09-28 17:13 UTC, DecathectZero commented
bors r+

2023-09-28 17:24 UTC, closed without merging

2023-10-04 08:02 UTC, andreasmartin commented
@viniciusdacal and @DecathectZero, I had to revert this commit (7bec1d4681a327ebe184a1eb9c673ff7ddff2bc8) because it was breaking the Dialog API requests such as:
```bash
curl -L '/state/user/userid/interact' `
-H 'Authorization: VF.DM.xx.xx' `
-H 'accept: application/json' `
-H 'content-type: application/json' `
-H 'versionID: development' `
-d '
{
  "action": {
    "type": "text",
    "payload": "Hi"
  }
}
'
```
With your changes, I received the following:
```JSON
{
    "name": "verror",
    "message": "Cannot resolve project version, please verify that your API key is correct.",
    "requestID": "nCfPsSE7ux"
}
```