Pedro/moderation llm calls/pl 553
voiceflow/general-runtime pull request #597
Opened 2023-09-28 20:06 UTC by pmvrmc

**Fixes or implements PL-553**

### Brief description. What is this change?
We need to add a LLM Moderation call to OpenAI for all models (even the ones that are not from OpenAI). This means that the OpenAI client must always be there for models.

Added a new Unleah client

Tweaked the AI client to be a dynamic instead of static service so that it can support FF via unleash.

Created a new service AISynthesis that pulls some util fns into it so that it can call the new dynamix AI client.

Tweaked some other util fns to make proper use of these new client/service accordingly.

2023-09-28 20:25 UTC, zhihil approved these changes

2023-09-28 21:12 UTC, Diophontine commented on lib/clients/contentModeration/openai/openai.ts
> +      log.warn(`[moderation error] input=${failedModeration.input} | categories=${failedModerationCategories}`);
@pmvrmc can you add the project id too?

2023-10-02 14:20 UTC, pmvrmc commented on lib/clients/contentModeration/openai/openai.ts
> +      log.warn(`[moderation error] input=${failedModeration.input} | categories=${failedModerationCategories}`);
ofc! I figure out  the best way to do that

2023-10-06 15:33 UTC, zhihil requested changes

2023-10-06 15:33 UTC, zhihil commented on lib/clients/ai/ai-model.interface.ts
> +export const GPT4_ABLE_PLAN = new Set(['old_pro', 'old_team', 'pro', 'team', 'enterprise']);
Should use the `PlanType` enum from `@voiceflow/internal`
```ts
import { PlanType } from "@voiceflow/internal";

export const GPT4_ABLE_PLAN = new Set([ PlanType.OLD_PRO, PlanType.OLD_TEAM, PlanType.PRO, PlanType.TEAM, PlanType.ENTERPRISE ]);
```

2023-10-06 15:33 UTC, zhihil commented on lib/clients/ai/openai/gpt.ts
> -    if (isAzureBasedGPTConfig(config)) {
This refactor of the `if`-`else` statement for choosing the Azure client vs. the OpenAI client might be incorrect and may cause a significant regression. 

The Azure client is used by default, I think for performance reasons. However, GPT-4 is not available on Azure, so we need to use the OpenAI client. With the way that the code is refactor, does this still occur? 

It looks like at `lib/clients/ai/index.ts`, we initialize a single OpenAI client which use either the Azure client or the OpenAI client, but not both. What we want is that there are at least two different clients, an OpenAI client for GPT-4 and an Azure client for everything else. With this change, we either:

1. Regress all clients to the OpenAI one, which incurs latency
2. Force the GPT-4 code onto the Azure client, which does not support GPT-4

Do we have confirmation that GPT-4 is available on Azure to make this change? I'm just checking this right now to make sure GPT-4 isn't broken by this change.

cc @DecathectZero

2023-10-06 16:04 UTC, zhihil commented on lib/services/runtime/handlers/aiResponse.ts
> +      projectID: runtime.project?._id,
Small style change:
```ts
const projectID = runtime.project?._id;
const generativemodel = runtime.services.ai.get(..., { projectID, .... });
const kbModel = runtime.services.ai.get(..., { projectID, ... });
```

2023-10-06 16:04 UTC, zhihil commented on lib/services/runtime/handlers/aiSet.ts
> +    const generativeModel = runtime.services.ai.get(node.model, { projectID: runtime.project?._id, workspaceID });
Same style change here

2023-10-06 21:08 UTC, zhihil commented on lib/clients/ai/openai/gpt.ts
> -    if (isAzureBasedGPTConfig(config)) {
I've tested the behaviour and I think we should fix the refactor as I mentioned above.

For some reason, the Azure client is able to resolve GPT-4 requests, even though we've never deployed a GPT-4 model on the cloud platform. Based on my tests, it looks your refactor is causing Azure client to fallback on GPT-3.5 when we select GPT-4.

I tested the AI Response step with GPT-3 vs. GPT-3.5 vs. GPT-4 with and without your changes. I turned the temperature of the AI Response step to 0 to remove randomness. The result is that in the current `master`, GPT-4 has a noticeably higher latency and different output than GPT-3.5. With your changes meshed, GPT-4 and -3.5 have about the same latency and exactly the same output. So I suspect that this refactor is breaking GPT-4.

2023-10-09 13:22 UTC, pmvrmc commented on lib/clients/ai/openai/gpt.ts
> -    if (isAzureBasedGPTConfig(config)) {
good catch. address this gpt4 problem by making sure it always uses the "normal" openAI client instead of the azure one.

I also noticed there was some weird code on the gpt3.5 code, where the client used was not the one passed to the function but the one on `this.client`.

2023-10-10 15:28 UTC, pmvrmc commented
bors r+

2023-10-10 15:37 UTC, pmvrmc commented
bors r+

2023-10-10 16:05 UTC, Xavientois commented
bors r+

2023-10-10 16:16 UTC, closed without merging