feat: (feature flagged) Call FAQ endpoint first (NLU-902)
voiceflow/general-runtime pull request #599
Opened 2023-10-04 14:53 UTC by e-vandenberg

Adds a call to the new poc faq retrieval endpoint before hitting the KB. Now any KB hit will do the following:
1. call /retrieve/poc/faq to see if the question is an faq. Return the answer if so.
2. Otherwise call /retrieve (as usual) to search all chunks, not just faq.

`80627` is our Python KB Testing workspace. Behaviour for all other workspaces in all other environments remains the same.

- [x] Tested in preview, no match, and KB response. Tested for both flagged and non-flagged workspaces.
- [ ] Must not be merged before https://github.com/voiceflow/KnowledgeLake/pull/133 
- [ ] Must not be merged before https://github.com/voiceflow/creator-app/pull/7226

2023-10-05 19:49 UTC, zhihil requested changes

2023-10-05 19:49 UTC, zhihil commented on lib/services/runtime/handlers/utils/knowledgeBase/index.ts
> +const FAQ_FLAGGED_WORKSPACES_MAP = new Map<string, string[]>([[CloudEnv.Public, ['80627']]]);
Wait for this PR: https://github.com/voiceflow/general-runtime/pull/597/files to be merge in and use the Unleash client it adds instead of hardcoding the feature flag here.

2023-10-05 19:49 UTC, zhihil commented on lib/services/runtime/handlers/utils/knowledgeBase/index.ts
> +  if (FAQ_RETRIEVAL_ENDPOINT && (flaggedWorkspaces?.length === 0 || flaggedWorkspaces?.includes(String(workspaceID)))) {
Replace with a call to Unleash feature flagging.

2023-10-05 19:49 UTC, zhihil commented on lib/services/runtime/handlers/utils/knowledgeBase/index.ts
> +    type: 'knowledgeBase',
This needs to be defined as a new trace type.

The `TraceType` will need to be added here:
 https://github.com/voiceflow/libs/blob/c9c2430856bc5ce1c50d186280eab0218bdfeaf7/packages/base-types/src/node/utils/trace.ts#L3

The object schema as a file in `libs/packages/base-types/src/node/knowledgeBase.ts`, following the example of this:

https://github.com/voiceflow/libs/blob/master/packages/base-types/src/node/speak.ts

2023-10-05 19:49 UTC, zhihil commented on lib/services/runtime/handlers/utils/knowledgeBase/index.ts
> +  } as any);
When the new trace type is defined, remove every `as any` cast in this file.

2023-10-05 19:53 UTC, e-vandenberg commented on lib/services/runtime/handlers/utils/knowledgeBase/index.ts
> +const FAQ_FLAGGED_WORKSPACES_MAP = new Map<string, string[]>([[CloudEnv.Public, ['80627']]]);
🥳 finally unleash in general-runtime

2023-10-05 19:54 UTC, e-vandenberg commented on lib/services/runtime/handlers/utils/knowledgeBase/index.ts
> +    type: 'knowledgeBase',
thanks for the references!

2023-10-11 19:31 UTC, zhihil approved these changes
Minor styling comment, but besides that approved:

2023-10-11 19:31 UTC, zhihil commented on lib/services/runtime/handlers/utils/knowledgeBase/index.ts
> +  host && port ? new URL(`${scheme}://${host}:${port}/poc/retrieve/faq`).href : null;
Should remove the duplication of 
```ts
new URL(`${scheme}://${host}:${port}
```
between `RETRIEVE_ENDPOINT` and `FAQ_RETRIEVAL_ENDPOINT`

2023-10-11 19:57 UTC, e-vandenberg commented
bors r+

2023-10-11 20:07 UTC, closed without merging