feat: implement NATO/APCO slot types (CORE-4839)
voiceflow/general-runtime pull request #60
Opened 2021-02-11 15:21 UTC by jgoping

**Fixes or implements CORE-4839 and CORE-4840**
https://voiceflow.atlassian.net/browse/CORE-4839
https://voiceflow.atlassian.net/browse/CORE-4840

### Brief description. What is this change?
Implements NATO/APCO slot type in a new handler, SlotsService.

### Implementation details. How do you make this change?
- SlotsService combines the NATO/APCO words identified by LUIS together with their first letters. entity.rawValue contains the words to parse and entity.value will store the result. Ex: rawValue: [['November'],['India'],['Charlie'],['Echo']] -> value: 'NICE'. The only exceptions to taking the first letter of the strings is '00' and '000', these stay the same.
- Unit tested the SlotService handler

### Related PRs
| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

### Checklist

- [ ✅  ] title of PR reflects the branch name
- [ ✅  ] all commits adhere to conventional commits
- [ ✅  ] appropriate tests have been written
- [ ✅  ] all the dependencies are upgraded

2021-02-24 16:03 UTC, leartgjoni-voiceflow requested changes

2021-02-24 16:03 UTC, leartgjoni-voiceflow commented on lib/services/slots/index.ts
> +            entity.value = entity.rawValue.reduce((acc, cur) => (cur[0] === '00' || cur[0] === '000' ? acc + cur[0] : acc + cur[0][0]), '');
1. based on [here](https://github.com/voiceflow/general-types/pull/45) `rawValue` can also be a string, shouldn't we also handle that case `entity.value = entity.rawValue[0]`. i.e `entity.rawValue = 'alpha'` => `entity.value = 'a';`
2. instead of comparing `'00' || '000'` manually, we can make it easier to extend in the future by creating an array `arr = ['00','000']` and check `arr.includes(cur[0])`

2021-02-25 06:02 UTC, DecathectZero approved these changes

2021-02-25 20:58 UTC, merged

2021-02-25 21:01 UTC, vf-service-account commented
:tada: This PR is included in version 1.27.0 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.27.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: