feat: use versioned KB if available (nlu-906)
voiceflow/general-runtime pull request #605
Opened 2023-10-18 15:30 UTC by e-vandenberg

- Added a check to make sure that DM API key, projectID and versionID are consistent when passed
- default to version level KB settings if available

2023-11-09 17:18 UTC, theProf requested changes

2023-11-09 17:18 UTC, theProf commented on lib/middlewares/auth.ts
> +  verifyParamConsistency = (
few notes on this middleware: 

```
const verifyParamConsistency = (
  // if you want it flexible, is accepting a single function okay for you? it 
  // can have the contract of setting those params, but has less overhead 
  // than 3 simple funcs
  mapFromRequest: (
    req: Request,
  ) => { projectID: string; auth: string; versionID: string },
) => {
  return async (req: Request, _res: Response, next: Next) => {
    try {
      const { projectID, auth, versionID } = mapFromRequest(req);

      const api = await this.services.dataAPI.get();
      const authenticatedProject = auth ? await api.getProject(auth) : null;
      const version = versionID ? await api.getVersion(versionID) : null;

      // i find naming in the positive is more readable in usage. 
      // "isInConsistent" leads to possible double negatives when doing if (!isInConsistent)
      const isConsistent = [
        projectID,
        authenticatedProject?._id,
        version?.projectID,
      ].filter((item) => !!item) // return boolean for filter
        // removed length check because you will always have at least projectID(?)
        .every((item) => item == projectID); // since you know what you're comparing to, don't rely on order of the array. if ALL are the correct projectID also reads better

      if (!isConsistent) {
        // more specific error, caught and transformed in catch
        throw new VError("Inconsistent projectIDs");
      }
    } catch (err) {
      // is there a difference between `next(Error)` and just throwing?
      return next(new VError("Unauthorized", VError.HTTP_STATUS.UNAUTHORIZED));
    }

    // if we get here, all worked out
    next();
  };
};
```

```
middlewares.auth.verifyParamConsistency(
  (req: Request) => ({
    projectID: req.body.projectID,
    auth: req.headers.authorization,
    versionID: req.body.versionID,
  }),
);
```

2023-11-09 20:00 UTC, e-vandenberg commented on lib/middlewares/auth.ts
> +  verifyParamConsistency = (
I agree with most of these points, but I left the order based comparison because in theory this should also allow consistency checks for someone who supplies only DM API key and versionID, and doesn't supply projectID

2023-11-10 08:03 UTC, theProf commented on lib/middlewares/auth.ts
> +  verifyParamConsistency = (
i think I need a bit more clarity here, on what are the valid scenarios and what are not. 
```
u: undefined
  projectID | DM Key  | versionID | isConsistent
============|=========|===========|=============
      u     |    u    |     u     | true
      u     |    u    |     1     | true
*     u     |    1    |     1     | true
      u     |    1    |     u     | true
*     1     |    1    |     u     | true
*     1     |    1    |     1     | true
*     1     |    u    |     1     | true
      1     |    u    |     u     | true

* more than 1 ID exists, add cases for different
      u     |    1    |     2     | false
      u     |    2    |     1     | false
      1     |    2    |     u     | false
      2     |    1    |     u     | false
      1     |    1    |     2     | false
      1     |    2    |     1     | false
      1     |    2    |     2     | false
      2     |    2    |     1     | false
      2     |    1    |     2     | false
      2     |    1    |     1     | false
      1     |    u    |     2     | false
      2     |    u    |     1     | false
```

If the assumption is (considering the DM Key as an "ID"): "any combination of at least 1 ID(s) is valid as long as they are the same", then what you're actually looking at is a `Set` and can shorten down to:

```
      const projectIDs = new Set([
        projectID,
        authenticatedProject?._id,
        version?.projectID,
      ].filter((item) => !!item));

      // 1 and exactly 1 unique ID
      const isConsistent = projectIDs.size == 1;
```

I'm unsure of the typings of those 3 ids right now, but they'll need to be cast in the mapping to the Set if not the same

2023-11-10 13:51 UTC, e-vandenberg commented on lib/middlewares/auth.ts
> +  verifyParamConsistency = (
yep that's exactly it, I've implemented this solution, much cleaner 😀

I appreciate the help!

2023-11-10 14:05 UTC, theProf approved these changes

2023-11-10 15:53 UTC, merged

2023-11-10 15:58 UTC, vf-service-account commented
:tada: This PR is included in version 1.186.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@voiceflow/general-runtime/v/1.186.0)
- [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.186.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: