feat: remove prompt leaks from response (VF-000)
voiceflow/general-runtime pull request #637
Opened 2023-12-04 13:56 UTC by e-vandenberg

Remove anything that occurs after a prompt leak regex match in a KB response. 

Remove old KB retry, users that want the improved experience should update their KB step.

2023-12-04 14:00 UTC, e-vandenberg commented on lib/services/aiSynthesis/index.ts
> +  private readonly REGEX_PROMPT_LEAK = /\s*#+\s?(query|instructions|reference)/i;
regex explanation: 

any whitespace, followed by one or more `#`, followed by 0 or 1 whitespace, followed by case-insensitive `query` OR `instructions` OR `reference`.

example matches:

`## Query`
`###instructions`
`\n## reference`

2023-12-04 14:49 UTC, theProf requested changes

2023-12-04 15:26 UTC, e-vandenberg commented on lib/services/aiSynthesis/index.ts
> +  private readonly REGEX_PROMPT_LEAK = /\s*#+\s?(query|instructions|reference)/i;
The only prompt leaks we've actually seen have 0 whitespace in between the ### and the header since the prompt follows this structure:

```
##Reference Information:
${chunks}

##Instructions:
...

##Query:
${query}
```

I added the single whitespace match just because I can imagine the possibility that the LLM might have been trained on some markdown that had the whitespace like `## Title`.

It's not likely that the hallucination will be something like `##                Query`

2023-12-04 15:28 UTC, e-vandenberg commented on lib/services/aiSynthesis/index.ts
> +  private removePromptLeak(output: string | null) {
in between the gate and `removePromptLeak(response.output)` we have `response.output = filterNotFound(response.output)` which may return `null`

2023-12-04 15:30 UTC, e-vandenberg commented on lib/services/aiSynthesis/index.ts
> +    return (segments?.length && segments[0]) || null;
yeah the replace makes more sense, and thanks for the regex pointers! had to switch the ending to `[\s\S]*` otherwise a response with newlines wouldn't match properly i.e.

```
correct answer here

##Query:
hallucination
more hallucination
```

2023-12-04 15:31 UTC, e-vandenberg commented on lib/services/aiSynthesis/index.ts
>        response.output = this.filterNotFound(response.output.trim());
the LLM response might have unnecessary whitespace, so when we pass to `filterNotFound` we strip it. `filterNotFound` will return either the string that was passed, or `null` if the input string contains some form of `NOT_FOUND`. So the `.trim()` permeates since `response.output` is now trimmed.

I'll trim once at the start for readability

2023-12-11 19:44 UTC, DecathectZero approved these changes

2023-12-11 19:51 UTC, e-vandenberg commented
bors r+

2023-12-11 20:02 UTC, theProf approved these changes

2023-12-11 20:05 UTC, e-vandenberg commented
bors r+

2023-12-11 20:26 UTC, e-vandenberg commented
bors r+

2023-12-11 20:40 UTC, closed without merging