feat: API Key Verification (CORE-5221)
voiceflow/general-runtime pull request #65
Opened 2021-02-19 16:37 UTC by jgoping

**Fixes or implements CORE-5221**

### Brief description. What is this change?
Allows for API key support when hitting the interact endpoint.

For req with origin voiceflow.com, dataAPI uses server-data-api. Otherwise, it uses creator-api and attaches the API key that the user request should have. The API key could come from an environment variable, or overrode by one in the request header.

This keeps server-data-api as our internal interface to the db and creator-api as the external interface protected by auth_vf or api-key.

### Implementation details. How do you make this change?
DataAPI is now a class instead of a function, which creates all three APIs if it has the information to. When an API call needs to be made, get() is called, which takes in the authorization (API key or auth_vf) and the origin of the request and determines which API it should make the call to.

CREATOR_APP_ENDPOINT is a new environment variable which needs to be updated in production. This is needed so that dataAPI can use server-data-api if a request's origin is CREATOR_APP_ENDPOINT.

### Related PRs
| branch              | PR          |
| ------------------- | ----------- |
| runtime | [link](url) |
| api-sdk     | [link](url) |

### Checklist

- [ ✅  ] title of PR reflects the branch name
- [ ✅  ] all commits adhere to conventional commits
- [ ✅  ] appropriate tests have been written
- [ ✅  ] all the dependencies are upgraded

2021-02-19 17:07 UTC, leartgjoni-voiceflow requested changes

2021-02-19 17:07 UTC, leartgjoni-voiceflow commented on lib/clients/dataAPI.ts
> +    return this.creatorDataApi;
I think this might be a problem. Here we are re-using and updating the same obj possibly between multiple requests. In case of a race condition, you could have req1 having their apiClient authorization updated by req2 before req1's call to creator-api is sent. I think a better way is on dataAPI.get() to generate creatorDataApi on the fly. This will also remove the need for modifying `creatorDataAPI` in `runtime`.

2021-02-19 17:07 UTC, leartgjoni-voiceflow commented on lib/controllers/interact.ts
> +    return turn.resolve({ state, request, versionID, data: { locale, authorization, origin } });
I'd be better to wrap `authorization` and `origin` in a parent object, just for organization

2021-02-19 20:12 UTC, jgoping commented on config.ts
> +  CREATOR_APP_ENDPOINT: getOptionalProcessEnv('CREATOR_APP_ENDPOINT'),
Fixed

2021-02-19 20:12 UTC, jgoping commented on lib/clients/dataAPI.ts
> +      this.creatorDataApi = new API.CreatorDataApi({ endpoint: `${CREATOR_API_ENDPOINT}/v2`, authorization: CREATOR_API_AUTHORIZATION ?? undefined });
Fixed

2021-02-19 20:12 UTC, jgoping commented on lib/clients/dataAPI.ts
> +    return this.creatorDataApi;
Fixed

2021-02-19 20:12 UTC, jgoping commented on lib/controllers/interact.ts
> +    return turn.resolve({ state, request, versionID, data: { locale, authorization, origin } });
Fixed

2021-02-19 22:24 UTC, leartgjoni-voiceflow requested changes

2021-02-19 22:24 UTC, leartgjoni-voiceflow commented on lib/services/runtime/index.ts
> +    }
I think this means we are only setting it once with whatever `context.data.api` we have for that first request. Instead we should just construct the new client on the fly inside of handle everytime. `handle` gets called once per request

2021-02-23 17:01 UTC, jgoping commented on lib/services/runtime/index.ts
> +    }
Yeah, it was getting set with the updated context.data.api in createRuntime() but this code isn't very clear. Updated it now to construct the client each time.

2021-02-23 20:02 UTC, leartgjoni-voiceflow approved these changes

2021-02-24 02:34 UTC, DecathectZero approved these changes

2021-02-24 16:12 UTC, merged

2021-02-24 16:19 UTC, vf-service-account commented
:tada: This PR is included in version 1.25.0 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: