feat: llm intent classification (PL-844)
voiceflow/general-runtime pull request #736
Opened 2024-03-28 15:46 UTC by theProf

**Fixes or implements PL-844**

### Brief description. What is this change?

### Implementation details. How do you make this change?

### Setup information

### Deployment Notes

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

2024-04-01 17:22 UTC, theProf commented on package.json
> +    "test:greg": "NODE_ENV=test ts-mocha --paths --opts ./config/tests/mocha.opts --watch"
nope, that snuck in, thanks

2024-04-02 16:00 UTC, trs commented on lib/services/classification/predictor.class.ts
> +          // TODO: remove magic number
A few outstanding todos.

2024-04-02 16:05 UTC, theProf commented on lib/services/classification/prompt-wrapper-executor.ts
> +  // if (!isStringReference(result)) {
i'll need help with this file. The original code we paired on had it returning a `Reference` and this checked if it referenced a string value before derefing, but the `result` is just the value returned and not a reference. I'm not as confident with the isolated-vm code given the maneuvering that went on to get execution in the first place, if someone would be able to lend a hand here

2024-04-02 16:11 UTC, theProf commented on lib/services/nlu/nlc.ts
>    dmRequest?: BaseRequest.IntentRequestPayload
this is all still used for nlc, we use `handleNLCCommand`

2024-04-02 16:12 UTC, trs requested changes

2024-04-02 16:12 UTC, trs commented on tests/lib/services/classification/prompt-wrapper-executor.test.ts
> +import { expect } from 'chai';
This file isn't being tested, it needs to end in `.unit.ts`.

These tests are also failing, the `executePromptWrapper` result is always `undefined`.

2024-04-02 17:59 UTC, vf-service-account commented
Creation of review environment failed! See details here: https://github.com/voiceflow/general-runtime/actions/runs/8527178194

2024-04-02 18:14 UTC, vf-service-account commented
Dev environment review-cool-tree created!
Preview available at: https://creator-review-cool-tree.us.development.voiceflow.com

2024-04-03 01:13 UTC, DecathectZero commented on lib/services/classification/prompt-wrapper-executor.ts
> +import { EXECUTION_TIMEOUT_MS, MEMORY_LIMIT_MB } from './promot-wrapper.const';
typo in the file name

2024-04-03 15:42 UTC, trs commented
Split up:

https://github.com/voiceflow/general-runtime/pull/743
https://github.com/voiceflow/general-runtime/pull/742
https://github.com/voiceflow/general-runtime/pull/744
https://github.com/voiceflow/general-runtime/pull/745
https://github.com/voiceflow/general-runtime/pull/746
https://github.com/voiceflow/general-runtime/pull/747
https://github.com/voiceflow/general-runtime/pull/748

2024-04-03 15:42 UTC, closed without merging