fix: predicator
voiceflow/general-runtime pull request #746
Opened 2024-04-03 05:35 UTC by DecathectZero

2024-04-03 17:31 UTC, DecathectZero commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/746?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#748** <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/748?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#747** <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/747?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#746** <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/746?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#745** <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/745?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#744** <a href="https://app.graphite.dev/github/pr/voiceflow/general-runtime/744?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `tyler/prompt-wrapper-executor/PL-844`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DecathectZero and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-03 18:58 UTC, theProf requested changes

2024-04-03 18:58 UTC, theProf commented on lib/services/classification/predictor.class.ts
> +        excludeFilteredIntents: false,
I had these flipped wrong: 
1. Top 10 intents (update `Predictor::nlu`)
```
filteredIntents: [],
excludeFilteredIntents: true
```

2. Slot filling (update `Predictor::fillSlots`)
```
filteredIntents: [<single intent>],
excludeFilteredIntents: false,
```

2024-04-03 21:26 UTC, theProf approved these changes

2024-04-04 00:06 UTC, DecathectZero commented
bors r+

2024-04-04 00:22 UTC, closed without merging