feat: tts handler decoupling (CORE-5254)
voiceflow/general-runtime pull request #75
Opened 2021-03-05 16:24 UTC by jgoping

**Fixes or implements CORE-5254**

### Brief description. What is this change?
The TTS handler in general-service is creating traces for both Speak Steps and Audio Steps. This tight coupling has already caused problems in runtime-client-js, where you can’t shut off the generation of TTS audio files, without also shutting off the code that parses the audio file url from the Audio Step.

### Implementation details. How do you make this change?
Creates a new Audio handler to deal with setting the src for audio traces and setting the types within the payloads of speak traces.

### Related PRs

| branch              | PR          |
| ------------------- | ----------- |
| other_pr_production | [link](url) |
| other_pr_master     | [link](url) |

### Checklist

- [ ✅  ] title of PR reflects the branch name
- [ ✅  ] all commits adhere to conventional commits
- [ ✅  ] appropriate tests have been written
- [ ] all the dependencies are upgraded

2021-03-05 17:16 UTC, zhihil requested changes

2021-03-05 17:16 UTC, zhihil commented on tests/lib/services/audio/index.unit.ts
> +            message: '',
`message: ''` is redundant because it's already in `malformedTrace2.payload`

2021-03-08 14:34 UTC, jgoping commented on lib/services/audio/index.ts
> +          type: SpeakType.MESSAGE,
Fixed

2021-03-08 14:34 UTC, jgoping commented on tests/lib/services/audio/index.unit.ts
> +            message: '',
Fixed

2021-03-08 20:24 UTC, zhihil approved these changes

2021-03-08 20:54 UTC, merged

2021-03-08 20:57 UTC, vf-service-account commented
:tada: This PR is included in version 1.29.0 :tada:

The release is available on [GitHub release](https://github.com/voiceflow/general-runtime/releases/tag/v1.29.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: