feat: remove generic templates for base-types update (PL-753)
voiceflow/general-runtime pull request #790
Opened 2024-04-23 21:12 UTC by zhihil

**Fixes or implements PL-753**

### Brief description. What is this change?

Remove generic instance to accommodate changes to the base-types.

### Implementation details. How do you make this change?

### Setup information

N/A

### Deployment Notes

N/A

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

2024-04-25 18:56 UTC, zhihil reviewed
Context:

2024-04-25 18:56 UTC, zhihil commented on lib/services/runtime/index.ts
> +      runtime.variables.set(VoiceflowConstants.BuiltInVariable.LAST_UTTERANCE, request.payload?.label);
`.label` is already potentially undefined, so the optional chaining shouldn't cause a huge deviation from existing behaviour.

2024-04-25 18:56 UTC, zhihil commented on lib/services/aiAssist.ts
> +      return request.payload?.label ?? null;
`.label` here was already potentially `undefined`, so adding this optional chaining should not create big issues.

2024-04-25 18:56 UTC, zhihil commented on lib/services/runtime/types.ts
> +export const isIntentRequest = (request?: RuntimeRequest): request is BaseRequest.IntentRequest =>
The `| null` here is redundant because `RuntimeRequest` already comes with `| null`.

2024-04-26 08:10 UTC, pmvrmc commented on lib/services/runtime/types.ts
> +  !!request && isTextRequest(request) && typeof request.payload === 'string';
arent we missing `DTO.isTextRequest` here? otherwise this will make an infinite loop

2024-04-26 19:18 UTC, zhihil commented on lib/services/runtime/types.ts
> +  !!request && isTextRequest(request) && typeof request.payload === 'string';
You're right.

2024-04-29 15:55 UTC, zhihil commented on lib/services/runtime/types.ts
> +  !!request && DTO.isTextRequest(request);
The `typeof request.payload === 'string'` check is redundant.

2024-04-29 20:29 UTC, zhihil commented on lib/services/slots/index.ts
> +    if (!this.isLUISIntentRequest(context.request)) {
This is legacy (possibly unused) code which expects a value that doesn't define the required property `value` on slots. 

I don't think we should make `value` optional to accommodate this old type, so I've instead created a legacy type guard to allow the code to continue working.

2024-04-30 15:50 UTC, zhihil commented on lib/controllers/interact.ts
> +    }
Various controller methods have been updated to add Zod parsing to the request objects. This ensures that the incoming request data is valid and adapted when necessary, e.g, intent request objects may lack the required `entities` and `query` properties and the DTO provides default values for them.

2024-04-30 15:53 UTC, zhihil commented on lib/services/runtime/types.ts
> -
Many of these type-guards have been deleted and replaced with type-guards from the DTO package, which have more stringent validation requirements.

2024-04-30 18:51 UTC, trs approved these changes
This could cause some unintended issues with peoples requests, we'll definitely want to keep an eye on requests.

2024-04-30 18:51 UTC, trs commented on lib/services/aiAssist.ts
> +    if (DTO.isLegacyIntentRequest(request)) {
Curious about the reason to have these under `DTO` rather than imported directly.

2024-05-02 20:31 UTC, trs requested changes

2024-05-02 20:31 UTC, trs commented on lib/controllers/interact/index.ts
> +    const action = await AnyRequestDTO.parseAsync(req.body.action);
Could update the above `InteractRequestBody` to have the `AnyRequestDTO`, and not have to do parsing here.

2024-05-03 15:26 UTC, zhihil commented on lib/services/aiAssist.ts
> +    if (DTO.isLegacyIntentRequest(request)) {
It was to disambiguate it from the type guards that are in `general-runtime`. It's a style that's also used on `creator-app` to provide clearer separation between what Voiceflow code belongs to what package.

Is it fine to adopt this convention for DTOs here?

2024-05-03 16:46 UTC, trs approved these changes

2024-05-06 15:46 UTC, zhihil commented
bors r+

2024-05-06 15:52 UTC, zhihil commented
bors r+

2024-05-07 15:27 UTC, zhihil commented
bors r+

2024-05-07 17:53 UTC, zhihil commented
bors r+

2024-05-07 18:05 UTC, closed without merging