feat: support streaming with knowledge base (PL-987)
voiceflow/general-runtime pull request #814
Opened 2024-05-13 15:56 UTC by trs

2024-05-16 18:55 UTC, trs commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +      super.error(new Error('BufferedReducerSubject'));
I tried completing the stream, but the downstream use case would just freeze. This way it throws and I catch it.

2024-05-16 18:59 UTC, trs commented on lib/services/runtime/handlers/aiResponse/model.ts
> +import { CompletionPrivateHTTPControllerGenerateChatCompletionStream200 as ChatCompletionStream } from '@voiceflow/sdk-http-ml-gateway/generated';
This was moved directly from `aiRespopnse/index.ts`

2024-05-16 18:59 UTC, trs commented on lib/services/runtime/handlers/aiResponse/knowledge-base.ts
> +import { deepVariableSubstitution } from '@voiceflow/common';
Moved from `aiResponse/index.ts` and refactored to support streaming

2024-05-17 09:59 UTC, pmvrmc commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +    if (result === 'stop') {
maybe replace this 'stop' with a const/enum/symbol for clarity?

2024-05-17 09:59 UTC, pmvrmc commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +    const result = this.predicate(this.buffer);
a bit confused here, shouldnt the predicate run before the accumulator?

so only if the predicate returns true we actually run the accumulator.

2024-05-17 09:59 UTC, pmvrmc commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +    if (result === 'stop') {
its a bit weird that the predicate returns true/false/stop.

would it make sense instead to just return true/false and do a try/catch around it to get the 'stop' usecase?

then the code that calls the buffer would throw the error instead of returning 'stop'. also I guess the error message could be better than just the class name

2024-05-17 09:59 UTC, pmvrmc commented on lib/services/aiSynthesis/index.ts
> +        if (this.filterNotFound(resp.output ?? '') === null) return 'stop';
we shouldnt need the `?? ''` here, its already on the previous line

2024-05-17 09:59 UTC, pmvrmc commented on lib/services/aiSynthesis/index.ts
> +        // Stop stream all together if output is a bad phrase
I would replace the "bad phrase" comment by "not found phrase"

2024-05-17 09:59 UTC, pmvrmc commented on lib/services/aiSynthesis/index.ts
> +      (resp) => {
the resp here is really the buffer right? would it make sense to name this variable buffer?

2024-05-17 12:29 UTC, theProf commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +    const result = this.predicate(this.buffer);
the order makes sense as is because we want to check the result of appending the new/next token and seeing if that's a bad phrase. so on the second emission (first: "NO", second: "T_") we want to send `NOT_` to the `predicate` instead of just `NO` which has already been checked

2024-05-17 12:34 UTC, theProf commented on lib/services/aiSynthesis/index.ts
> +      (resp) => {
correct, the `resp` here is the bufferd `acc: KBResponse`. I don't think `buffer` would make sense, as that's good for the generic implementation of `BufferedReducerSubject`, but here we have more context as to what _exactly_ the `buffer` is. 
I agree that `resp` isn't the best name, as it's not a single `resp`, but the buffered/accumulated `resp`s so far. but without coffee and a tenuous grasp on language itself, i have no good suggestion

2024-05-17 13:26 UTC, theProf commented on lib/services/aiSynthesis/index.ts
> +      }
lets keep this custom Subject usage as immutable as possible, avoid mutate methods like `.push` and opt for spread, `concat`, `reduce`, etc
```suggestion
      (buffer, value) => ({
        chunks: (buffer.chunks || []).concat(value.chunks ?? []),
        output: (buffer.output ?? "") + (value.output ?? ""),
        answerTokens: buffer.answerTokens + value.answerTokens,
        queryTokens: buffer.queryTokens + value.queryTokens,
        tokens: buffer.tokens + value.tokens,
        model: value.model,
        multiplier: value.multiplier,
        faqSet: value.faqSet,
      })
```

2024-05-17 13:26 UTC, theProf commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
this will definitely require unit testing. may be worth looking at the marble test frameworks if we start rolling more of our own / using rxjs more

2024-05-17 13:26 UTC, theProf commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +      delete this.buffer;
should probably delete _after_ the error throw (the error throw sets some other vars that start locking up access, so we'll want to delete _after_ we're sure no one is going to try to access)

may want to add a check and free in the unsubscribe too. we rely on state and emitted values to do clean up right now

2024-05-17 16:08 UTC, trs commented on lib/services/aiSynthesis/index.ts
> +      (resp) => {
It _may_ be a buffered response, but it could be just a plain response. Either way, it's the same type `KBResponse`, and is treated the same as a non buffered response.

2024-05-17 16:30 UTC, pmvrmc commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +      super.error(err);
not sure if applicable, but should we return after `super.error(err);` inside the catch?

I know in this case it doesnt relaly matter, but what Im worried is someone in the future adding something outside of the try/catch. In said scenearion in case of an error it would run both the catch and rhe new code. Also that future possible error wont show up on PR review as the catch clause is not touched, but it will impact the flow.

2024-05-17 16:53 UTC, theProf commented on lib/services/aiSynthesis/index.ts
> +      (resp) => {
i can accept that, i redact my request for change

2024-05-17 18:21 UTC, trs commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +    this.buffer = this.buffer ? this.accumulator(this.buffer, value) : value;
That can be done in the `accumulator` when implementing, yeah?

2024-05-17 18:40 UTC, theProf requested changes

2024-05-17 18:40 UTC, theProf commented on tests/lib/services/aiSyntesis/buffer-reduce.subject.unit.ts
> +            err instanceof BufferedReducerStopException ? throwError(() => 'error') : throwError(() => err)
`throwError` is overkill for this case (usually for when a subject or high order observable unwrapping, etc), you can just regular `throw`. And since this is just testing, it doesn't even need to be an `Error` type. 

bonus fun fact: `throwError` takes a factory OR the thing to throw, so `throwError(new Error('beep'))` or even `throwError('error')` would have sufficed

```suggestion
            err instanceof BufferedReducerStopException ? throw 'error') : throw err
```

2024-05-17 18:48 UTC, trs commented on tests/lib/services/aiSyntesis/buffer-reduce.subject.unit.ts
> +            err instanceof BufferedReducerStopException ? throwError(() => 'error') : throwError(() => err)
Apparently passing a value to `throwError` is deprecated, the factory is the recommended way.
But yeah, overkill is fair.

2024-05-17 18:55 UTC, theProf commented on tests/lib/services/aiSyntesis/buffer-reduce.subject.unit.ts
> +            err instanceof BufferedReducerStopException ? throwError(() => 'error') : throwError(() => err)
https://github.com/ReactiveX/rxjs/blob/7.8.1/src/internal/observable/throwError.ts#L104

well i'll be, makes sense. thanks!

2024-05-17 18:56 UTC, theProf approved these changes

2024-05-17 20:13 UTC, trs commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +      super.error(err);
Seems like a really odd thing to guard against IMO.

2024-05-17 20:15 UTC, theProf commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +      super.error(err);
if it's being removed by linting, lets go with that

2024-05-17 20:15 UTC, theProf commented on lib/services/aiSynthesis/buffer-reduce.subject.ts
> +  unsubscribe(): void {
nice

2024-05-22 17:18 UTC, trs commented
bors merge

2024-05-22 17:29 UTC, closed without merging