fix: remove slot filling from nlu prediction service (PL-1109)
voiceflow/general-runtime pull request #830
Opened 2024-05-28 18:47 UTC by theProf

### Brief description. What is this change?

Remove slot filling from nlu service and leave solely to dialog service

### Implementation details. How do you make this change?

there are 2 places we do slot filling:
first in the nlu service
the in the dialog manager if needed
They both do the same fillSlots call (now, in my test). but the main difference is that the dialog manager adds a prefix to the utterance.
I'm unsure why the NLU performs poorly on the number match (only takes the first 3?) given the same intent and utterance (without prefix). but the solution i'll be pushing is to remove slot filling from the nlu service and leave all slot filling to be done in the dialog manager until a proper investigation can be done to tweak/optimize/etc

### Checklist

- [x] Appropriate tests have been written
- [ ] bors try

2024-05-28 19:08 UTC, theProf commented
bors try

2024-05-28 19:24 UTC, trs commented on lib/services/classification/predictor.class.ts
> +      this.debug('NLC' as DebugType);
We don't want to expose NLC to the end user

2024-05-28 19:31 UTC, theProf commented on lib/services/classification/predictor.class.ts
> +      this.debug('NLC' as DebugType);
whoops, missed a debug line. thanks

2024-05-30 18:10 UTC, trs requested changes

2024-05-30 18:10 UTC, trs commented on lib/services/dialog/index.ts
> +          const filledSlots = await predictor.fillSlots(`${prefix} ${query}`, {
Move this back to the `predict` call.

2024-05-30 18:10 UTC, trs commented on lib/services/dialog/index.ts
> +              params: { confidence: 0.6 },
Is `version.platformData.settings.intentConfidence` still valid to use here?

2024-05-30 18:33 UTC, theProf commented on lib/services/dialog/index.ts
> +              params: { confidence: 0.6 },
i wouldn't trust it as it's not a feature we currently explicitly support (storing both nlu + hybrid settings to switch between), you currently are expected to lose changes. Default (as in your PR) seems most solid right now

2024-05-31 14:45 UTC, theProf commented on lib/services/classification/predictor.class.ts
> +    const nluPrediction = this.props.isTrained && (await this.nlu(utterance, { limit: 10 }));
this should switch back to `this.options` with a default somewhere

2024-05-31 14:48 UTC, theProf commented on lib/services/dialog/index.ts
> +        const scopedSlots = scopedIntent?.slots?.map((slot) => slots?.find((entity) => entity.key === slot.id));
```suggestion
        const scopedSlots = scopedIntent?.slots?.map((slot) => slots?.find((entity) => entity.key === slot.id)).filter(Boolean);
```
then below you don't have to `slot?.name`

2024-05-31 14:51 UTC, theProf commented on lib/services/dialog/index.ts
> +            const existingEntity = slotFillingRequest.payload.entities.find((entity) => entity.name === slot.name);
pending size we may want to compute this once into a Map

2024-05-31 15:17 UTC, trs commented on lib/services/dialog/index.ts
> +        const scopedSlots = scopedIntent?.slots?.map((slot) => slots?.find((entity) => entity.key === slot.id));
Typescript isn't smart enough to know that slot is not undefined here

2024-05-31 15:17 UTC, trs commented on lib/services/dialog/index.ts
> +            const existingEntity = slotFillingRequest.payload.entities.find((entity) => entity.name === slot.name);
For sure, this code is gross and I think deserves a refactor

2024-05-31 15:28 UTC, theProf commented on lib/services/dialog/index.ts
> +            const existingEntity = slotFillingRequest.payload.entities.find((entity) => entity.name === slot.name);
for later days

2024-05-31 15:44 UTC, trs commented
bors try

2024-05-31 16:15 UTC, closed without merging